title: LargeLanguageMind
description: >-
A process-driven research journal tracing how my evolving understanding of intelligence,
cognition, and machine learning emergesâ€”from intuition, cross-domain connections, 
and reasoning, to formal concepts.


theme: jekyll-theme-minimal

# GitHub Pages base URL
url: "https://theminddeveloper.github.io"
baseurl: "/LargeLanguageMind"

github:
  is_project_page: true
  repository_url: https://github.com/theMindDeveloper/LargeLanguageMind

markdown: kramdown
kramdown:
math_engine: null
